### ISSUE TITLE
Get rid of shelljs

### ISSUE THREAD

**Issue by eldoy** [eldoy/extras#3]
Prefer built in libraries to reduce package size, get rid of shelljs

**Comment by acmb** [comment]
Hi, @eldoy!

This is done. Please let me know if you feel that something should be changed or improved.
This may affect several other packages.

**Comment by eldoy** [comment]
If we're using spawn instead of NodeJS functions we're losing Windows compatibility... Not sure if that's important in the future but it wouldn't hurt.

I feel like these functions are redundant now, since we might as well just use `run`?

Should we just remove them? Or rewrite using `node:fs`?

**Comment by acmb** [comment]
@eldoy,

1. I think I saw some `spawn` option that would help with Windows compatibility. I could investigate that.
2. I guess using the functions can help with cleaner code. But it is true that we could simply use `run`.
3. Do you mean using `node:fs` for `file functions` and using `node:child_process` for `run` only?

**Comment by eldoy** [comment]
1. Don't think it's worth spending time on.
2. Yes.
3. Yes, that was what I initially thought of, that would give us windows compatibility too.

Let's think about it a while, it's not a priority. We don't have anything running on Windows atm anyway.
